### ISSUE TITLE
don't hotlink to the raw github version from the bookmarklet (fails strict mime type checking)

### ISSUE THREAD

**Issue by npdoty** [nytimes/svg-crowbar#11]
Per https://github.com/blog/1482-, GitHub is adding a header to prevent some browsers from executing scripts that are loaded from raw.github.com. As the bookmarklet dynamically loads the script from raw.github.com, the script fails to execute in those browsers. (For me, Chrome 36 is refusing to execute; while Firefox 34 Nightly runs it anyway.)

**Comment by hugolpz** [comment]
I just updated my code. Use `https://rawgit.com/` instead, and it works. See [this stackoverflow answer](http://stackoverflow.com/questions/18492617/#18502640), or [this live demo](https://rugger-demast.codio.io/front/_location_map-en.html)

```
    <a class="download ac-icon-download" href="javascript:javascript: (function () { var e = document.createElement('script'); if (window.location.protocol === 'https:') { e.setAttribute('src', 'https://rawgit.com/NYTimes/svg-crowbar/gh-pages/svg-crowbar.js'); } else { e.setAttribute('src', 'http://nytimes.github.com/svg-crowbar/svg-crowbar.js'); } e.setAttribute('class', 'svg-crowbar'); document.body.appendChild(e); })();"><!--⤋--><big>⇩</big> Download</a> -- Works on Chrome. Feedback welcome for others web browsers.
```

@shancarter : if doc is updated, this issue can be set as solve.

**Comment by shancarter** [comment]
I've updated the link to the https link on github.
