### ISSUE TITLE
Generated SVG is missing xmlns and xmlns:xlink attributes.

### ISSUE THREAD

**Issue by mbostock** [nytimes/svg-crowbar#2]
I noticed this while trying to crowbar the following SVGs:

  http://bl.ocks.org/mbostock/raw/3795544/

The resulting SVG files `svg` elements appeared as:

``` xml
<svg width="320" height="500" version="1.1">
```

However, the desired result includes xmlns and xmlns:xlink attributes:

``` xml
<svg width="320" height="500" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
```

Without these attributes, the SVG will not display properly.

**Comment by shancarter** [comment]
Thanks, should be fixed now
