### ISSUE TITLE
Download all option possible?

### ISSUE THREAD

**Issue by JeremyTBradshaw** [nytimes/svg-crowbar#27]
This is not really an issue, it's a feature request.  I have portal.azure.com in mind.  I want to get the SVG's so I can use them in my Visio diagrams.  There are 781 SVG's found!  So many that I can't move the Crowbar boxes out of each others' way so I can click the download button.

**Comment by Mancerrss** [comment]
Yea it would be nice if there will be a scan option and will let you download them all. Also even scan for SVGs hided in other frames or interaction events e.g. this SVg will only show when in mouse hover, so we don't have to time it

**Comment by ghost** [comment]
https://burninglizard.wordpress.com/2015/04/27/downloading-svg-automatically-with-svg-crowbar/

**Comment by JeremyTBradshaw** [comment]
Thanks.  I'll give that a try.  I guess I'll close the issue at this point as I forgot all about it.
