### ISSUE TITLE
Not installable in Chrome anymore?

### ISSUE THREAD

**Issue by bjlange** [nytimes/svg-crowbar#33]
Since upgrading to Chrome 69, I seem to not be able to install the bookmarklet anymore. I've tried dragging it to the bookmark bar and adding it through the menus, but neither seems to work..

**Comment by gurmanbh** [comment]
any update on this?

**Comment by amywc** [comment]
+1 Is there any update?

**Comment by joellacarman** [comment]
I too couldn't add the bookmark but just uninstalled and reinstalled Chrome and works fine for me now. @amywc @gurmanbh

**Comment by amywc** [comment]
I updated my Chrome and now it works.... hope that helps @joellacarman !

**Comment by bjlange** [comment]
Yes it seems the latest Chrome re-allows installing and using Javascript bookmarklets. Phew! Closing...
