### ISSUE TITLE
Loading the d3 in https gets blocked

### ISSUE THREAD

**Issue by riston** [nytimes/svg-crowbar#6]
I am sure you already know this issue:

`[blocked] The page at 'https://*' was loaded over HTTPS, but ran insecure content from 'http://d3js.org/d3.v3.min.js': this content should also be loaded over HTTPS.`

**Comment by mbostock** [comment]
It would be nice if GitHub pages supported HTTPS. But at any rate Crowbar could use CDNJS instead of d3js.org which does.

**Comment by mbostock** [comment]
Fixed in f4a58619f98bb8835f69e6c88f39570c144a112d using CDNJS.
